# Generated by Django 5.1.3 on 2024-11-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted date')),
                ('description', models.TextField(verbose_name='Description of the job')),
                ('summary', models.TextField(verbose_name='Summery')),
                ('logo_url', models.URLField(verbose_name='Logo URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostings.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='Application date')),
                ('status', models.CharField(max_length=50, verbose_name='Status of application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostings.candidate', verbose_name='Candidate')),
                ('jobposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostings.jobposting', verbose_name='Jobposition')),
            ],
        ),
    ]
